---
title: "deception_acc_test"
author: "C Armour"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

require(ggplot2)
require(sf)
require(terra)
require(tidyverse)
require(caret)


knitr::opts_chunk$set(echo = TRUE)
```

```{r}

## Read in the gpkg layers
gpkg_path <- "C:/Users/ccarmour.stu/OneDrive - Government of BC/PEM/Deception_AOI/Deception_maps.gpkg"
lyrs <- st_layers(gpkg_path)
rcl.tbl <- read.csv("C:/Users/ccarmour.stu/OneDrive - Government of BC/PEM/Deception_AOI/Deception_orig-new_Label_reclass_v3.csv", na.strings = "") %>%
  tibble()

```


```{r orig}

tem.pem <- st_read(gpkg_path, layer = lyrs$name[1]) %>%
  # st_cast(to = "POLYGON") %>%
  mutate(across(where(is.character), na_if, "")) %>%
  select(c(BGC_LBL, SDEC_1, SITES_LBL1, SDEC_2, SITES_LBL2, SDEC_3, SITES_LBL3))

st_write(tem.pem, dsn = 'C:/Users/ccarmour.stu/OneDrive - Government of BC/PEM/Deception_AOI/40_accuracy_testing/tem_pem_orig.shp',
         append = FALSE)

exp.pem <- st_read(gpkg_path, layer = lyrs$name[2]) %>%
  # st_cast(to = "POLYGON") %>%
  mutate(across(where(is.character), na_if, "")) %>%
  select(c(BGC_LBL, response_combo_bcgs_key_all_x))

st_write(exp.pem, dsn = 'C:/Users/ccarmour.stu/OneDrive - Government of BC/PEM/Deception_AOI/40_accuracy_testing/exp_pem_orig.shp',
         append = FALSE)

mle.pem <- st_read(gpkg_path, layer = lyrs$name[3]) %>%
  # st_cast(to = "POLYGON") %>%
  mutate(across(where(is.character), na_if, "")) %>%
  select(response_combo_bcgs_key_all_x)

st_write(mle.pem, dsn = 'C:/Users/ccarmour.stu/OneDrive - Government of BC/PEM/Deception_AOI/40_accuracy_testing/mle_pem_orig.shp',
         append = FALSE)

```


```{r reclass}

tem.pem.rcl <- tem.pem %>%
  filter(BGC_LBL != "SBSdk") %>%
  mutate(SITES_LBL1_full = case_when(!is.na(SITES_LBL1) ~ str_c(BGC_LBL, SITES_LBL1, sep = "_"), TRUE ~ NA_character_),
         SITES_LBL2_full = case_when(!is.na(SITES_LBL2) ~ str_c(BGC_LBL, SITES_LBL2, sep = "_"), TRUE ~ NA_character_),
         SITES_LBL3_full = case_when(!is.na(SITES_LBL3) ~ str_c(BGC_LBL, SITES_LBL3, sep = "_"), TRUE ~ NA_character_)) %>%
  left_join(y = rcl.tbl[c("label.orig", "matched")], by = join_by(SITES_LBL1_full == label.orig), keep = TRUE, na_matches = "never") %>%
  rename(rspns_t_1 = matched) %>%
  left_join(y = rcl.tbl[c("label.orig", "matched")], by = join_by(SITES_LBL2_full == label.orig), keep = TRUE, na_matches = "never") %>%
  rename(rspns_t_2 = matched) %>%
  left_join(y = rcl.tbl[c("label.orig", "matched")], by = join_by(SITES_LBL3_full == label.orig), keep = TRUE, na_matches = "never") %>%
  rename(rspns_t_3 = matched) %>%
  select(c(BGC_LBL, SDEC_1, SDEC_2, SDEC_3, rspns_t_1, rspns_t_2, rspns_t_3)) %>%
  pivot_longer(cols = c(rspns_t_1, rspns_t_2, rspns_t_3), names_to = "SITE.CALL", values_to = "rspns_t") %>%
  pivot_longer(cols = c(SDEC_1, SDEC_2, SDEC_3), names_to = "SDEC.CALL", values_to = "SDEC.PROP") %>%
  mutate(call.match = str_split(SITE.CALL, pattern = "_", simplify = T)[,3],
         prop.match = str_split(SDEC.CALL, pattern = "_", simplify = T)[,2]) %>%
  filter(as.numeric(call.match) == as.numeric(prop.match)) %>%
  select(!c(call.match, prop.match))

st_write(tem.pem.rcl,
         dsn = 'C:/Users/ccarmour.stu/OneDrive - Government of BC/PEM/Deception_AOI/40_accuracy_testing/tem_pem_rcl.shp',
         append = FALSE)

exp.pem.rcl <- exp.pem %>%
  filter(BGC_LBL != "SBSdk") %>%
  left_join(y = rcl.tbl[c("label.orig", "matched")],
            by = join_by(response_combo_bcgs_key_all_x == label.orig),
            keep = FALSE,
            na_matches = "never") %>%
  rename(rspns_x = matched) %>%
  select(BGC_LBL, rspns_x)

st_write(exp.pem.rcl,
         dsn = 'C:/Users/ccarmour.stu/OneDrive - Government of BC/PEM/Deception_AOI/40_accuracy_testing/exp_pem_rcl.shp',
         append = FALSE)

mle.pem.rcl <- mle.pem %>%
  left_join(y = rcl.tbl[c("label.mle", "matched")],
            by = join_by(response_combo_bcgs_key_all_x == label.mle),
            keep = FALSE,
            na_matches = "never") %>%
  rename(rspns_m = matched) %>%
  mutate(BGC_LBL = case_when(rspns_m != "nonfor" ~ str_split(rspns_m, pattern = "_", simplify = TRUE)[,1],
                             TRUE ~ "Unspecified")) %>% 
  select(BGC_LBL, rspns_m)

st_write(mle.pem.rcl,
         dsn = 'C:/Users/ccarmour.stu/OneDrive - Government of BC/PEM/Deception_AOI/40_accuracy_testing/mle_pem_rcl.shp',
         append = FALSE)


```

```{r}

area.tem <- tem.pem.rcl %>%
  mutate(area.polygon.call = (SDEC.PROP/10)*as.numeric(st_area(.))) %>%
  st_drop_geometry() %>%
  group_by(rspns_t) %>%
  summarize(area.totals.tem = sum(area.polygon.call , na.rm = T)) %>%
  filter(!is.na(rspns_t))

area.exp <- exp.pem.rcl %>%
  mutate(area.polygon = as.numeric(st_area(.))) %>%
  st_drop_geometry() %>%
  group_by(rspns_x) %>%
  summarize(area.totals.exp = sum(area.polygon, na.rm = T)) %>%
  filter(!is.na(rspns_x))

area.mle <- mle.pem.rcl %>%
  mutate(area.polygon = as.numeric(st_area(.))) %>%
  st_drop_geometry() %>%
  group_by(rspns_m) %>%
  summarize(area.totals.mle = sum(area.polygon, na.rm = T)) %>%
  filter(!is.na(rspns_m))


```

```{r}

int.mle.tem <- st_intersection(mle.pem.rcl, st_geometry(tem.pem))

area.mle.tem <- int.mle.tem %>%
  mutate(area.polygon = as.numeric(st_area(.))) %>%
  st_drop_geometry() %>%
  group_by(rspns_m) %>%
  summarize(area.totals.mle = sum(area.polygon, na.rm = T))


area.totals.mt <- full_join(area.tem, area.mle.tem, join_by(rspns_t == rspns_m), keep = TRUE, na_matches = "never") %>%
  rename(tem.area = area.totals.tem, mle.area = area.totals.mle) %>%
  pivot_longer(c(tem.area, mle.area), names_to = "source", values_to = "areas") %>%
  mutate(rspns = case_when(!is.na(rspns_m) ~ rspns_m, TRUE ~ rspns_t),
         BGC_LBL = case_when(rspns != "nonfor" ~ str_split(rspns, pattern = "_", simplify = TRUE)[,1],
                             TRUE ~ "Unspecified")) %>%
  replace_na(list(areas = 0L)) %>%
  select(c(rspns, source, areas, BGC_LBL)) %>%
  group_by(source)


ggplot(data = area.totals.mt, aes(x = rspns, y = areas, fill = source)) +
  geom_bar(stat = "identity", position = "dodge") +
  ggtitle("Area of Site Series by Subzone") +
  # scale_y_log10() +
  theme(axis.text.x = element_text(angle = 60, hjust=1))


```

```{r}

int.mle.exp <- st_intersection(mle.pem.rcl, st_geometry(exp.pem))

area.mle.exp <- int.mle.exp %>%
  mutate(area.polygon = as.numeric(st_area(.))) %>%
  st_drop_geometry() %>%
  group_by(rspns_m) %>%
  summarize(area.totals.mle = sum(area.polygon, na.rm = T))


area.totals.mx <- full_join(area.exp, area.mle.exp, join_by(rspns_x == rspns_m), keep = TRUE, na_matches = "never") %>%
  rename(exp.area = area.totals.exp, mle.area = area.totals.mle) %>%
  pivot_longer(c(exp.area, mle.area), names_to = "source", values_to = "areas") %>%
  mutate(rspns = case_when(!is.na(rspns_m) ~ rspns_m, TRUE ~ rspns_x),
         BGC_LBL = case_when(rspns != "nonfor" ~ str_split(rspns, pattern = "_", simplify = TRUE)[,1],
                             TRUE ~ "Unspecified")) %>%
  replace_na(list(areas = 0L)) %>%
  select(c(rspns, source, areas, BGC_LBL)) %>%
  group_by(source)


ggplot(data = area.totals.mx, aes(x = rspns, y = areas, fill = source)) +
  geom_bar(stat = "identity", position = "dodge") +
  ggtitle("Area of Site Series by Subzone") +
  # scale_y_log10() +
  theme(axis.text.x = element_text(angle = 60, hjust=1))

```

